# Generated by Django 3.1 on 2020-08-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskDiscription',
            new_name='taskDesc',
        ),
    ]
